version: '3.8'
services:

  tuum-postgres:
    image: postgres:15.3
    container_name: tuum-postgres
    volumes:
      - tuum-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5488:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    restart: unless-stopped

  tuum-rabbitmq:
    image: rabbitmq:3.9.29
    container_name: tuum-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    restart: unless-stopped

  tuum-project:
    build: ./
    container_name: tuum-project
    ports:
      - 8095:8095
    depends_on:
      - tuum-postgres
      - tuum-rabbitmq
    restart: unless-stopped

volumes:
  tuum-data:
